# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='shared_to',
            field=models.ManyToManyField(related_name='shared_posts', to='blog.Blog'),
        ),
    ]
